# FindWayland.cmake
find_package(PkgConfig REQUIRED)
pkg_check_modules(WAYLAND_CLIENT REQUIRED wayland-client)
pkg_check_modules(WAYLAND_CURSOR REQUIRED wayland-cursor)
pkg_check_modules(WAYLAND_EGL REQUIRED wayland-egl)
pkg_check_modules(XKBCOMMON REQUIRED xkbcommon)

find_path(WAYLAND_CLIENT_INCLUDE_DIR
  NAMES wayland-client.h
  PATHS ${WAYLAND_CLIENT_INCLUDE_DIRS})

find_library(WAYLAND_CLIENT_LIBRARY
  NAMES wayland-client
  PATHS ${WAYLAND_CLIENT_LIBRARY_DIRS})

find_path(WAYLAND_CURSOR_INCLUDE_DIR
  NAMES wayland-cursor.h
  PATHS ${WAYLAND_CURSOR_INCLUDE_DIRS})

find_library(WAYLAND_CURSOR_LIBRARY
  NAMES wayland-cursor
  PATHS ${WAYLAND_CURSOR_LIBRARY_DIRS})

find_path(WAYLAND_EGL_INCLUDE_DIR
  NAMES wayland-egl.h
  PATHS ${WAYLAND_EGL_INCLUDE_DIRS})

find_library(WAYLAND_EGL_LIBRARY
  NAMES wayland-egl
  PATHS ${WAYLAND_EGL_LIBRARY_DIRS})

find_path(XKBCOMMON_INCLUDE_DIR
  NAMES xkbcommon/xkbcommon.h
  PATHS ${XKBCOMMON_INCLUDE_DIRS})

find_library(XKBCOMMON_LIBRARY
  NAMES xkbcommon
  PATHS ${XKBCOMMON_LIBRARY_DIRS})

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(Wayland DEFAULT_MSG
  WAYLAND_CLIENT_LIBRARY WAYLAND_CLIENT_INCLUDE_DIR
  WAYLAND_CURSOR_LIBRARY WAYLAND_CURSOR_INCLUDE_DIR
  WAYLAND_EGL_LIBRARY WAYLAND_EGL_INCLUDE_DIR
  XKBCOMMON_LIBRARY XKBCOMMON_INCLUDE_DIR)

mark_as_advanced(WAYLAND_CLIENT_INCLUDE_DIR WAYLAND_CLIENT_LIBRARY
  WAYLAND_CURSOR_INCLUDE_DIR WAYLAND_CURSOR_LIBRARY
  WAYLAND_EGL_INCLUDE_DIR WAYLAND_EGL_LIBRARY
  XKBCOMMON_INCLUDE_DIR XKBCOMMON_LIBRARY)
